# 项目相关配置
PMIT:
  # 英文名称
  name: PMIT_bakstage
  # 中文名称
  cnName: PMIT项目管理系统
  # 版本
  version: 1.0.0

#配置端口
server:
  port: 8080

# Spring配置
spring:
  profiles:
    # 环境 dev:开发环境|test：测试环境|prod：线上环境
    active: dev
    # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

# 配置Mybatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.isoftstone.pmit
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# rest 配置
rest:
  ReadTimeout: 35000
  ConnectTimeout: 5000




